### ISSUE TITLE
Read more... on posts

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#157]
When a text post is too long, we want it to be collapsible through a read more button.

Or anyone better ideas to make reading long texts nice?

**Comment by oliverzet** [comment]
I'm not sure if it is a good idea but you could let long texts just fade out after maybe 500 or so characters.
A tap on the text would then open a kind of full screen reading mode with adjustable font size. Since some people with impaired vision have stated that texts are hard to read with the current font size, it might be a good idea to have such a "read mode" as general option when tapping a text.
