### ISSUE TITLE
App cache is massive.

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-app#404]
I'm not sure if this is a bug introduced with videos or already existed before with images, but the documents and data consumed by the apps are HUUUGE.

We need to make sure the limits we have in place are working both for images and videos.

![IMG_7F179B1CFBF7-1](https://user-images.githubusercontent.com/12737509/65687922-75dbb900-e06a-11e9-812d-7f1ddf4c9aeb.jpeg)

**Comment by lifenautjoe** [comment]
CC @uiboy @999eagle @Komposten in case anyone has an idea of what might be going on

**Comment by 999eagle** [comment]
As data is a lot more accessible on desktop than on mobile I noticed this a few times already. The underlying issue is mostly a directory called `imagecache` inside each platform's cache. There's also a `libCachedImageData` directory, but that is rather small.

The `imagecache` contains a lot of images, some even multiple times with different names. The oldest file in that directory on my PC is the Okuna logo and was created on 2019-07-13 and never accessed again. It seems like the image caching mechanism downloads a lot of images, but once you open post comments, the image is downloaded again and cached with a different name. If you close post comments and open them again, the image is downloaded and cached a third time. None of these images are ever accessed again and the cache is also never cleared, so it just grows indefinitely and it grows more quickly than necessary.

**Comment by lifenautjoe** [comment]
Thank you Sophie! Will check the `AdvancedNetworkImage` library we're using for this.

**Comment by 999eagle** [comment]
Monitoring that directory in real time while scrolling through my timeline shows that sometimes the same image shows up twice at the same time in the `imagecache`, even though there's only one post with that image. Closing the app and opening it again adds the same images again to the cache.

**Comment by Komposten** [comment]
Another factor, albeit maybe not quite as big, is temporary files. When media is picked using the media picker we create a file in the "application document directory". When the post is uploaded we compress the media and place the compressed file in the same directory. And, on Android, when media is shared to Okuna we copy the media file to the application's external directory, so this has the same implication as selecting using the media picker.

The only time one of these "temporary" files is removed is, as far as I know, if you remove media from a post in the create post modal. If you close the modal using the `x` or proceed to share the post, the files will remain indefinitely.

This is after I've cleared all data, logged in, and uploaded 5 videos to Okuna. Pay attention to the "Data" value as opposed to the "Cache".
![image](https://user-images.githubusercontent.com/7335682/65696405-70399f80-e079-11e9-8e6b-06f6740c273d.png)

**Comment by lifenautjoe** [comment]
I've made this bug a critical. We need to check what is going wrong with the cached images.

Image URLs from posts have querystrings with signatures from AWS to get temporal access to the file. If these are stored as different files based on this, everytime you refresh the timeline, you will get different "files" as the signature will differ.

Other thing is checking what is the current max of the cache of these images and finally, doing some cleanup tasks when it comes to creating the post and all of the temporal files it involves.

Would also be good to have a button in the developer settings to clear all the temp files. I believe the current one only clears the cache.

**Comment by uiboy** [comment]
@Komposten @999eagle thanks guys your research was helpful 🙏
